# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: DeleteFiles@1
    inputs:
      Contents: '*' 
      RemoveSourceFolder: true
  
  - task: UseDotNet@2
    inputs:
      version: '6.0.x'
      
  - script: dotnet restore
    displayName: 'dotnet restore'

  - script: dotnet build --configuration $(buildConfiguration) -f net6.0 --no-restore /m:1
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Pay-As-You-Go(08bdc99d-5bfa-4a62-b80c-d54507e085a6)'
      appType: 'webApp'
      appName: 'orionapi-webapp-dev'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'
